version: '2'
services:

  # The Application
  rauxa_app:
    build:
      context: ./
      dockerfile: app.dev.dockerfile
    working_dir: /var/www
    volumes:
      - ../../:/var/www
    env_file:
      - ../../.env

  # The Web Server
  rauxa_web:
    build:
      context: ./
      dockerfile: web.dev.dockerfile
    working_dir: /var/www
    volumes_from:
      - rauxa_app
    ports:
      - 8080:80

  # The Database
  rauxa_database:
    image: mysql:5.6
    volumes:
      - dbdata:/var/lib/mysql
    env_file:
        - ../../.env
    ports:
        - "33061:3306"

volumes:
  dbdata:
